title: Yonglan Liu-Blog
description: Computational Chemistry | FEP | AI for Drug Discovery
theme: minima

author: Yonglan Liu
email: liuyonglan04@gmail.com

markdown: kramdown


header_pages:
  - index.md
  - projects/index.md
  - fep/index.md
  - ai-drug-discovery/index.md
  - about.md

