title: Yonglan Liu-Blog
description: Drug Discovery
theme: minima

markdown: kramdown

header_pages:
  - index.md
  - projects/index.md
  - fep/index.md
  - ai-drug-discovery/index.md
  - blog/index.md
  - about.md

